language: python
name: integration-continue
on: [push]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run nosetests
      with:
        python-version: '3.8'
