language: python
name: integration-continue
on: [push]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Script
        run: |
          pipenv run nosetests
